# git-cliff ~ configuration file
# https://git-cliff.org/docs/configuration


[changelog]
# A Tera template to be rendered for each release in the changelog.
# See https://keats.github.io/tera/docs/#introduction
body = """
{%- if version -%}
    ## [{{ version | trim_start_matches(pat="v") }}] - {{ timestamp | date(format="%Y-%m-%d") }}
{%- else -%}
    ## [unreleased]
{%- endif %}

{% for group, commits in commits | group_by(attribute="group") -%}
    ### {{ group | striptags | trim | upper_first }}

    {% for commit in commits -%}
        - {% if commit.scope %}*({{ commit.scope }})* {% endif -%}
            {%- if commit.breaking %}[**breaking**] {% endif -%}
            {{ commit.message | upper_first }}
            {%- if commit.remote.username %} by @{{ commit.remote.username }}{%- endif -%}
            {%- if commit.remote.pr_number %} in #{{ commit.remote.pr_number }}{%- endif %}
    {% endfor %}
{% endfor -%}
{%- if github.contributors | filter(attribute="is_first_time", value=true) -%}
    ### New Contributors

    {% for contributor in github.contributors | filter(attribute="is_first_time", value=true) -%}
        - @{{ contributor.username }} made their first contribution
            {%- if contributor.pr_number %} in #{{ contributor.pr_number }}{%- endif %}
    {% endfor -%}
{%- endif -%}
"""
# Remove leading and trailing whitespaces from the changelog's body.
trim = true
# Render body even when there are no releases to process.
render_always = true
# An array of regex based postprocessors to modify the changelog.
postprocessors = [
    # Replace the placeholder <REPO> with a URL.
    { pattern = '<REPO>', replace = "https://github.com/NathanielJS1541/CV" },
]

[git]
# Parse commits according to the conventional commits specification.
# See https://www.conventionalcommits.org
conventional_commits = true
# Require all commits to be conventional.
# This is required by the lint-commits.yml GitHub Action workflow.
require_conventional = true
# An array of regex based parsers to modify commit messages prior to further processing.
commit_preprocessors = [
    # Replace issue numbers with link templates to be updated in `changelog.postprocessors`.
    { pattern = '#([0-9]+)', replace = "[#${1}](<REPO>/issues/${1})"},
    # Check spelling of the commit message using https://github.com/crate-ci/typos.
    # If the spelling is incorrect, it will be fixed automatically.
    #{ pattern = '.*', replace_command = 'typos --write-changes -' },
]
# Prevent commits that are breaking from being excluded by commit parsers.
protect_breaking_commits = true
# An array of regex based parsers for extracting data from the commit message.
# Assigns commits to groups.
# Optionally sets the commit's scope and can decide to exclude commits from
# further processing.
#
# Note that any changes here should be reflected in the CONTRIBUTING.md
# document.
commit_parsers = [
    { message = "^feat", group = "<!-- 0 -->üöÄ New Sections" },
    { message = "^fix", group = "<!-- 1 -->üêõ Amended Sections" },
    { message = "^docs", group = "<!-- 2 -->üìö Documentation" },
    { message = "^ci", group = "<!-- 3 -->üõ†Ô∏è CI/CD" },
    { message = "^style", group = "<!-- 4 -->üé® Styling" },
    { message = "^chore\\(release\\)", skip = true },
    { message = "^chore", group = "<!-- 5 -->‚öôÔ∏è Miscellaneous Tasks" },
    { message = "^revert", group = "<!-- 6 -->‚óÄÔ∏è Revert" },
    { message = ".*", group = "<!-- 7 -->üíº Other" },
]
# Exclude commits that are not matched by any commit parser.
filter_commits = false
# An array of link parsers for extracting external references, and turning them into URLs, using regex.
link_parsers = []
# Include only the tags that belong to the current branch.
use_branch_tags = false
# Order releases topologically instead of chronologically.
topo_order = false
# Order releases topologically instead of chronologically.
topo_order_commits = true
# Order of commits in each group/release within the changelog.
# Allowed values: newest, oldest
sort_commits = "oldest"
# Process submodules commits
recurse_submodules = false
